# Backend service definition

services:
  backend:
    build:
      context: ../ushadow/backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-backend
    env_file:
      - ../.env          # Environment configuration
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      # Server configuration
      - HOST=0.0.0.0
      - PORT=8000  # Internal port - always 8000
      - BACKEND_PORT=${BACKEND_PORT:-8000}  # External port - uses offset from .env
      - REDIS_URL=redis://redis:6379/${REDIS_DATABASE:-0}
      # Tailscale IP for node registration (set via .env or detected)
      - TAILSCALE_IP=${TAILSCALE_IP:-}
      # Tailscale container name for peer discovery (docker exec)
      - TAILSCALE_CONTAINER=tailscale
      # Host project root for docker compose volume mounts (required for service management)
      - PROJECT_ROOT=${PROJECT_ROOT:-${PWD}}
      # Compose project name for per-environment Tailscale containers
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-ushadow}
      # Environment name for unode display
      - ENV_NAME=${ENV_NAME:-}
      # Host machine hostname for Tailscale peer discovery
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      # Config directory location
      - CONFIG_DIR=/config
      - MONGODB_DATABASE=${MONGODB_DATABASE:-ushadow}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000,http://localhost:${WEBUI_PORT}}
      # Rich console width for logging (prevents log wrapping)
      - COLUMNS=200
      # Database configuration
      - POSTGRES_USER=${POSTGRES_USER:-ushadow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ushadow}
      - POSTGRES_DB=${POSTGRES_DB:-ushadow}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      # Keycloak SSO configuration
      # Backend reads via OmegaConf which interpolates these env vars in config.defaults.yaml
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://keycloak:8080}
      - KEYCLOAK_EXTERNAL_URL=${KEYCLOAK_EXTERNAL_URL:-http://localhost:8081}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-ushadow}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-ushadow-frontend}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:-}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
    volumes:
      - ../ushadow/backend:/app
      - ../config:/config  # Mount config directory (read-write for feature flags)
      - ../compose:/compose  # Mount compose files for service management
      - ../mycelia:/mycelia  # Mount mycelia for building mycelia-backend service
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.venv  # Mask host .venv - container uses its own venv from image
      # Docker socket for container management (Tailscale container control)
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ushadow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

networks:
  ushadow-network:
    name: ushadow-network
    external: true
