# Chronicle backend service definition with separate workers
# Environment variables are passed directly via docker compose subprocess env
# No .env files needed - CapabilityResolver provides all values
#
# Image Strategy:
#   - Submodule checked out: Builds from local source (./chronicle)
#   - Submodule missing: Pulls pre-built images from ghcr.io/ushadow-io/chronicle/*
#   - Uses pull_policy: build to prefer local builds when context exists

# =============================================================================
# USHADOW METADATA (ignored by Docker, read by ushadow backend)
# =============================================================================
x-ushadow:
  # Services share namespace with main ushadow for unified auth (AUTH_SECRET_KEY)
  chronicle-backend:
    display_name: "Chronicle api"
    description: "AI-powered voice journal and life logger with transcription and LLM analysis"
    requires: [llm, transcription]
    optional: [memory]  # Uses memory if available, works without it
    tags: ["voice", "journal", "ai", "transcription", "conversation", "audio"]
    # route_path: /chronicle  # Tailscale Serve route - all /chronicle/* requests go here
    exposes:
      - name: audio_intake
        type: audio
        path: /ws
        port: 8000  # Internal container port
        metadata:
          protocol: wyoming
          formats: [pcm, opus]
          codec_param: true  # Clients specify codec via ?codec=pcm or ?codec=opus
      - name: http_api
        type: http
        path: /
        port: 8000
      - name: health
        type: health
        path: /health
        port: 8000
  chronicle-workers:
    display_name: "Chronicle Workers"
    description: "Background workers for Chronicle (transcription, memory, audio processing)"
    requires: [llm, transcription]
  chronicle-webui:
    display_name: "Chronicle Web UI"
    description: "Web interface for Chronicle voice journal"
    requires: []

services:
  chronicle-backend:
    image: ghcr.io/ushadow-io/chronicle/backend:latest
    build:
      context: ../chronicle/backends/advanced
      dockerfile: Dockerfile
      target: dev
    pull_policy: build  # Build from source if context exists, otherwise pull from GHCR
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-chronicle-backend
    ports:
      - "${CHRONICLE_BACKEND_PORT:-8090}:8000"
    environment:
      # Infrastructure connections (from CapabilityResolver or defaults)
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - QDRANT_BASE_URL=${QDRANT_BASE_URL:-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}


      # LLM capability (from selected provider) - REQUIRED
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

      # Transcription capability (from selected provider)
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-}
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-deepgram}
      # Memory capability (optional, from selected provider)
      - MEMORY_PROVIDER=${MEMORY_PROVIDER:-openmemory_mcp}
      - MEMORY_SERVER_URL=${MEMORY_SERVER_URL:-}
      - OPENMEMORY_USER_ID=${ADMIN_EMAIL:-admin@example.com}

      # Security (from settings) - AUTH_SECRET_KEY is required for JWT auth
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - ACCEPTED_ISSUERS=${ACCEPTED_ISSUERS:-ushadow,chronicle}
      # CORS
      - CORS_ORIGINS=${CORS_ORIGINS:-*}

      

    volumes:
      # Data persistence
      - chronicle_audio:/app/audio_chunks
      - chronicle_data:/app/data
      - chronicle_debug:/app/debug_dir

      # Config directory - contains config files, feature flags, secrets, etc.
      # Mount entire ushadow config directory to override built-in configs
      - ${PROJECT_ROOT}/config:/app/config:ro

    networks:
      - ushadow-network

    # NOTE: Depends on shared infrastructure services (mongo, redis, qdrant)
    # These must be started separately via docker-compose.infra.yml
    # Cannot use depends_on for services in external compose files

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readiness"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  chronicle-workers:
    image: ghcr.io/ushadow-io/chronicle/backend:latest
    build:
      context: ../chronicle/backends/advanced
      dockerfile: Dockerfile
      target: prod
    pull_policy: build  # Build from source if context exists, otherwise pull from GHCR
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-chronicle-workers
    command: ["uv", "run", "python", "worker_orchestrator.py"]
    environment:
      # Infrastructure connections
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - QDRANT_BASE_URL=${QDRANT_BASE_URL:-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}

      # LLM capability
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

      # Transcription capability
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-}
      # - PARAKEET_ASR_URL=${PARAKEET_ASR_URL}
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-deepgram}
           # Memory capability (optional, from selected provider)
      - MEMORY_PROVIDER=${MEMORY_PROVIDER:-openmemory_mcp}
      - MEMORY_SERVER_URL=${MEMORY_SERVER_URL:-}
      - OPENMEMORY_USER_ID=${ADMIN_EMAIL:-admin@example.com}

      # Worker orchestrator configuration
      - WORKER_CHECK_INTERVAL=${WORKER_CHECK_INTERVAL:-10}
      - MIN_RQ_WORKERS=${MIN_RQ_WORKERS:-6}
      - WORKER_STARTUP_GRACE_PERIOD=${WORKER_STARTUP_GRACE_PERIOD:-30}
      - WORKER_SHUTDOWN_TIMEOUT=${WORKER_SHUTDOWN_TIMEOUT:-30}

    volumes:
      # Data persistence (shared with backend)
      - chronicle_audio:/app/audio_chunks
      - chronicle_data:/app/data
      - chronicle_debug:/app/debug_dir

      # Config directory
      - ${PROJECT_ROOT}/config:/app/config:ro

    networks:
      - ushadow-network

    restart: unless-stopped

  chronicle-webui:
    image: ghcr.io/ushadow-io/chronicle/webui:latest
    build:
      context: ../chronicle/backends/advanced/webui
      dockerfile: Dockerfile
    pull_policy: build  # Build from source if context exists, otherwise pull from GHCR
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-chronicle-webui
    ports:
      - "${CHRONICLE_WEBUI_PORT:-3080}:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:${CHRONICLE_PORT:-8090}
      - BACKEND_URL=${CHRONICLE_BACKEND_URL:-http://chronicle-backend:8000}
    networks:
      - ushadow-network
    depends_on:
      - chronicle-backend
    restart: unless-stopped

# Chronicle data volumes (local to this environment)
volumes:
  chronicle_audio:
    driver: local
  chronicle_data:
    driver: local
  chronicle_debug:
    driver: local

# Use existing shared infrastructure network
networks:
  ushadow-network:
    name: ushadow-network
    external: true
