# Mycelia - AI Memory and Timeline
# Self-hosted voice memo transcription, timeline, and memory system
#
# Usage:
#   docker compose -f compose/mycelia-compose.yml up -d
#
# Access:
#   - Web UI: http://localhost:${MYCELIA_FRONTEND_PORT:-18080}
#   - Backend API: http://localhost:${MYCELIA_BACKEND_PORT:-15173}

# =============================================================================
# USHADOW METADATA (ignored by Docker, read by ushadow backend)
# =============================================================================
x-ushadow:
  namespace: mycelia
  # Infra services to start before this compose (from docker-compose.infra.yml)
  infra_services: ["mongo", "redis"]
  mycelia-backend:
    display_name: "Mycelia"
    description: "Self-hosted AI memory and timeline - capture ideas via voice, screenshots, or text"
    requires: ["llm", "transcription", "audio_input"]
    provides: ["memory", "transcription", "timeline"]
    tags: ["ai", "memory", "voice", "transcription", "timeline"]
    wizard: "mycelia"  # ID of the setup wizard
  mycelia-frontend:
    display_name: "Mycelia Frontend"
    description: "Mycelia web interface"
  mycelia-python-worker:
    display_name: "Mycelia Python Worker"
    description: "Audio processing worker"

services:
  mycelia-frontend:
    build:
      context: ${PROJECT_ROOT:-..}/mycelia
      dockerfile: ./frontend/Dockerfile.${MYCELIA_FRONTEND_MODE:-dev}
    image: mycelia-frontend:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-mycelia-frontend
    ports:
      - "${MYCELIA_FRONTEND_PORT:-18080}:8080"
    volumes:
      - ${PROJECT_ROOT:-..}/mycelia/frontend:/app
      - ${PROJECT_ROOT:-..}/mycelia/myceliasdk:/app/myceliasdk
    environment:
      - MYCELIA_FRONTEND_MODE=dev  
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  mycelia-backend:
    build:
      context: ${PROJECT_ROOT:-..}/mycelia
      dockerfile: ./backend/Dockerfile
    image: mycelia-backend:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-mycelia-backend
    ports:
      - "${MYCELIA_BACKEND_PORT:-15173}:5173"
    command: deno task dev
    environment:
      # Application URLs
      - MYCELIA_URL=http://localhost:${MYCELIA_BACKEND_PORT:-15173}
      - MYCELIA_BACKEND_INTERNAL_URL=http://mycelia-backend:5173
      - MYCELIA_FRONTEND_HOST=http://localhost:${MYCELIA_FRONTEND_PORT:-18080}

      # Authentication
      - MYCELIA_TOKEN=${MYCELIA_TOKEN}
      - MYCELIA_CLIENT_ID=${MYCELIA_CLIENT_ID}
      - SECRET_KEY=${AUTH_SECRET_KEY}

      # Database Configuration - uses shared mongo from infra
      - DATABASE_NAME=${MYCELIA_DATABASE_NAME:-mycelia}
      - MONGO_URL=mongodb://mongo:27017/${MYCELIA_DATABASE_NAME:-mycelia}?directConnection=true

      # Redis Configuration - uses shared redis from infra
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

      # Python Worker
      - PYTHON_WORKER_URL=http://mycelia-python-worker:8000

      # LLM Provider Configuration
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}

      # Transcription Provider Configuration
      - TRANSCRIPTION_BASE_URL=${TRANSCRIPTION_BASE_URL}
      - TRANSCRIPTION_API_KEY=${TRANSCRIPTION_API_KEY}
      - TRANSCRIPTION_MODEL=${TRANSCRIPTION_MODEL}

      # OpenTelemetry
      - OTEL_DENO=${MYCELIA_OTEL_DENO:-false}
      - OTEL_SERVICE_NAME=mycelia
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=${MYCELIA_OTEL_EXPORTER_OTLP_ENDPOINT:-http://localhost:4318}

      # Application Config
      - LOG_LEVEL=${MYCELIA_LOG_LEVEL:-INFO}
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ${PROJECT_ROOT:-..}/mycelia/backend:/app
      - ${PROJECT_ROOT:-..}/mycelia/myceliasdk:/myceliasdk
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "deno", "eval", "const res = await fetch('http://localhost:5173/health'); Deno.exit(res.ok ? 0 : 1);"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.2'
          memory: 1G
    restart: unless-stopped

  mycelia-python-worker:
    build:
      context: ${PROJECT_ROOT:-..}/mycelia
      dockerfile: ./python/Dockerfile
    image: mycelia-python:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-mycelia-python-worker
    environment:
      - MYCELIA_URL=http://mycelia-backend:5173
      - SECRET_KEY=${AUTH_SECRET_KEY}
    volumes:
      - ${PROJECT_ROOT:-..}/mycelia/python:/app
      - mycelia_worker_data:/root/.cache
    networks:
      - infra-network
    depends_on:
      mycelia-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    restart: unless-stopped

networks:
  infra-network:
    name: infra-network
    external: true

volumes:
  mycelia_worker_data:
    driver: local
