# OpenMemory (mem0) service definition
# Graph-based memory with MCP support
# Environment variables are passed directly via docker compose subprocess env

# =============================================================================
# USHADOW METADATA (ignored by Docker, read by ushadow backend)
# =============================================================================
x-ushadow:
  namespace: openmemory
  # Infra services to start before this compose (from docker-compose.infra.yml)
  # To enable graph mode, add "neo4j" to infra_services and uncomment NEO4J_* env vars below
  infra_services: ["qdrant", "neo4j"]
  mem0:
    display_name: "OpenMemory"
    description: "Vector memory API with MCP support for persistent AI context"
    requires: [llm]
    provides: memory  # This service implements the 'memory' capability
  mem0-ui:
    display_name: "OpenMemory UI"
    description: "Web interface for browsing and managing OpenMemory graph"
    requires: []

services:
  mem0:
    image: ghcr.io/ushadow-io/u-mem0-api:v1.0.4
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-mem0
    pull_policy: always
    # Requires qdrant from infra (started via infra_services in x-ushadow)
    ports:
      - "${OPENMEMORY_PORT:-8765}:8765"
    environment:
      # Database configuration
      # SQLite (default, persisted in mem0_data volume): sqlite:////app/data/openmemory.db
      # PostgreSQL (when supported): postgresql://user:password@host:port/database
      - DATABASE_URL=${OPENMEMORY_DATABASE_URL:-sqlite:////app/data/openmemory.db}

      # Qdrant connection (from CapabilityResolver or defaults)
      - QDRANT_HOST=${QDRANT_HOST:-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}

      # LLM capability (from selected provider) - REQUIRED
      # Note: Empty default suppresses warnings; CapabilityResolver validates at start
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

      # Neo4j (for graph memory) - FEATURE FLAG: uncomment to enable graph mode
      - NEO4J_URL=${NEO4J_URL:-bolt://neo4j:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - NEO4J_DB=${NEO4J_DB:-neo4j}
    volumes:
      - mem0_data:/app/data
    networks:
      - ushadow-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8765/api/v1/config/'); exit(0)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mem0-ui:
    image: ghcr.io/ushadow-io/u-mem0-ui:v1.0.4
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-mem0-ui
    ports:
      - "3002:3000"
    environment:
      - VITE_API_URL=http://localhost:${OPENMEMORY_PORT:-8765}
      - API_URL=http://mem0:8765
      - NEXT_PUBLIC_USER_ID=${ADMIN_EMAIL:-admin@example.com}
    networks:
      - ushadow-network
    depends_on:
      - mem0
    restart: unless-stopped

networks:
  ushadow-network:
    name: ushadow-network
    external: true

volumes:
  mem0_data:
    driver: local
