version: '3.8'

# Share DMZ Compose Stack
#
# Minimal services for public share access via Tailscale Funnel.
# Deploy this stack to a "public" unode with zone=public label.
#
# Architecture:
# - Internet users → Tailscale Funnel (public unode)
# - share-dmz-frontend: Minimal React app (ShareViewPage + LoginPage only)
# - share-dmz-backend: Minimal FastAPI (share endpoints only)
# - Main ushadow backend accessed over private Tailnet

services:
  share-dmz-backend:
    image: ghcr.io/ushadow-io/ushadow-backend:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-share-dmz-backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      # MongoDB connection (shared with main ushadow for share tokens)
      MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb:27017}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-ushadow}

      # Main ushadow backend URL (over Tailnet)
      MAIN_BACKEND_URL: ${MAIN_BACKEND_URL:-http://ushadow-orange-backend:8000}

      # Keycloak (for authentication)
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-ushadow}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_DMZ_CLIENT_ID:-ushadow-dmz}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_DMZ_CLIENT_SECRET}

      # DMZ mode (only enable share endpoints)
      DMZ_MODE: "true"
      ALLOWED_ENDPOINTS: "/api/share/*,/health"

      # Rate limiting
      RATE_LIMIT_PER_MINUTE: ${DMZ_RATE_LIMIT:-30}
    networks:
      - ushadow-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "ushadow.service=share-dmz-backend"
      - "ushadow.zone=public"
      - "ushadow.env=${ENV_NAME:-orange}"

  share-dmz-frontend:
    image: ghcr.io/ushadow-io/ushadow-dmz-frontend:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-share-dmz-frontend
    restart: unless-stopped
    ports:
      - "5174:5173"
    environment:
      VITE_API_URL: http://share-dmz-backend:8000
      VITE_KEYCLOAK_URL: ${KEYCLOAK_SERVER_URL}
      VITE_KEYCLOAK_REALM: ${KEYCLOAK_REALM:-ushadow}
      VITE_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_DMZ_CLIENT_ID:-ushadow-dmz}
      VITE_DMZ_MODE: "true"
    networks:
      - ushadow-network
    depends_on:
      - share-dmz-backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "ushadow.service=share-dmz-frontend"
      - "ushadow.zone=public"
      - "ushadow.env=${ENV_NAME:-orange}"

  # Shared MongoDB (read-only access to share_tokens collection)
  mongodb:
    image: mongo:7
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-dmz-mongodb
    restart: unless-stopped
    volumes:
      - dmz-mongodb-data:/data/db
    networks:
      - ushadow-network
    command: ["--quiet"]
    labels:
      - "ushadow.service=dmz-mongodb"
      - "ushadow.zone=public"

  # Tailscale sidecar with Funnel enabled
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-dmz-tailscale
    restart: unless-stopped
    hostname: ${TAILSCALE_HOSTNAME:-ushadow-dmz}
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: "--advertise-tags=tag:dmz"
    volumes:
      - dmz-tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - ushadow-network
    command: tailscaled
    labels:
      - "ushadow.service=dmz-tailscale"
      - "ushadow.zone=public"

networks:
  ushadow-network:
    external: true
    name: ${NETWORK_NAME:-ushadow-network}

volumes:
  dmz-mongodb-data:
    name: ${COMPOSE_PROJECT_NAME:-ushadow}-dmz-mongodb-data
  dmz-tailscale-state:
    name: ${COMPOSE_PROJECT_NAME:-ushadow}-dmz-tailscale-state

# x-ushadow metadata for service discovery
x-ushadow:
  namespace: share-dmz
  description: "Share DMZ - Public-facing minimal services for conversation sharing"
  deployment_labels:
    zone: public
    funnel: enabled
  requires:
    - keycloak
    - mongodb
  provides: public-share-access
