# Ushadow self-deployment definition
# Use your local ushadow instance to deploy itself to Kubernetes!

# =============================================================================
# USHADOW METADATA (ignored by Docker, read by ushadow backend)
# =============================================================================
x-ushadow:
  ushadow-backend:
    display_name: "Ushadow Backend"
    description: "Service orchestration platform backend (FastAPI)"
    requires: []  # Ushadow is self-contained
    route_path: /api  # Tailscale route for API
  ushadow-frontend:
    display_name: "Ushadow Frontend"
    description: "Service orchestration platform UI (React)"
    requires: []

services:
  ushadow-backend:
    # Use pre-built image (built from source via build-ushadow-images.sh)
    image: anubis:32000/ushadow-backend:latest
    # Or build from source (uncomment and comment image above)
    # build:
    #   context: ../ushadow/backend
    #   dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-backend-k8s
    ports:
      - "8000:8000"
    environment:
      # ── Infrastructure URLs ───────────────────────────────────────────────
      - REDIS_URL=${REDIS_URL}

      # ── MongoDB Credentials ───────────────────────────────────────────────
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_AUTH_SOURCE=${MONGODB_AUTH_SOURCE}

      # ── Security ──────────────────────────────────────────────────────────
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}

      # ── Keycloak URLs (both change per environment) ───────────────────────
      # Internal URL: backend→Keycloak admin API (K8s FQDN)
      - KC_URL=${KC_URL}
      # Public URL: browser OAuth redirects and token issuer
      - KC_HOSTNAME_URL=${KC_HOSTNAME_URL}
      # ── Keycloak Credentials ──────────────────────────────────────────────
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}

      # ── K8s-specific ──────────────────────────────────────────────────────
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://ushadow-frontend.ushadow.svc.cluster.local}
      - KUBECONFIG_DIR=/app/data/kubeconfigs

    volumes:
      # Persistent data (kubeconfigs stored here)
      - ushadow-data:/app/data

    # NOTE: In K8s, we DON'T mount docker.sock or use docker-in-docker
    # Service management is handled via kubectl to the K8s API

    networks:
      - ushadow-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    restart: unless-stopped

  ushadow-frontend:
    # Use pre-built image (built from source via build-ushadow-images.sh)
    image: anubis:32000/ushadow-frontend:latest
    # Or build from source (uncomment and comment image above)
    # build:
    #   context: ../ushadow/frontend
    #   dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-frontend-k8s
    ports:
      - "3000:80"
    environment:
      - VITE_ENV_NAME=${VITE_ENV_NAME:-k8s}
      # BACKEND_HOST for nginx proxy (K8s service name)
      - BACKEND_HOST=${BACKEND_HOST:-ushadow-backend}
    networks:
      - ushadow-network
    depends_on:
      - ushadow-backend
    restart: unless-stopped

volumes:
  ushadow-config:
    driver: local
  ushadow-compose:
    driver: local
  ushadow-kubeconfigs:
    driver: local
  ushadow-data:
    driver: local

networks:
  infra-network:
    name: ushadow-network
    external: true
  ushadow-network:
    name: ushadow-network
    external: true
