x-ushadow:
  faster-whisper:
    display_name: "Faster Whisper"
    description: "Local speech-to-text with OpenAI-compatible API"
    requires: []
    provides: transcription
    tags: ["audio", "transcription", "local"]

services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: faster-whisper
    environment:
      - WHISPER__MODEL=${WHISPER_MODEL:-Systran/faster-whisper-base}
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - whisper_models:/root/.cache/huggingface
    ports:
      - "${WHISPER_PORT:-10300}:8000"
    networks:
      - ushadow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ushadow-network:
    name: ushadow-network
    external: true

volumes:
  whisper_models:
    driver: local