"""Contains all the data models used in inputs/outputs"""

from .access_urls import AccessUrls
from .access_urls_environments import AccessUrlsEnvironments
from .access_urls_environments_additional_property import AccessUrlsEnvironmentsAdditionalProperty
from .action_response import ActionResponse
from .api_keys_step import ApiKeysStep
from .api_keys_update_response import ApiKeysUpdateResponse
from .apply_defaults_api_providers_apply_defaults_mode_post_response_apply_defaults_api_providers_apply_defaults_mode_post import (
    ApplyDefaultsApiProvidersApplyDefaultsModePostResponseApplyDefaultsApiProvidersApplyDefaultsModePost,
)
from .auth_url_response import AuthUrlResponse
from .bearer_response import BearerResponse
from .body_auth_bearer_login_api_auth_jwt_login_post import BodyAuthBearerLoginApiAuthJwtLoginPost
from .body_auth_cookie_login_api_auth_cookie_login_post import BodyAuthCookieLoginApiAuthCookieLoginPost
from .body_register_dockerhub_service_api_github_import_dockerhub_register_post import (
    BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPost,
)
from .body_register_dockerhub_service_api_github_import_dockerhub_register_post_env_vars_type_0_item import (
    BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostEnvVarsType0Item,
)
from .body_register_dockerhub_service_api_github_import_dockerhub_register_post_ports_type_0_item import (
    BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostPortsType0Item,
)
from .body_register_dockerhub_service_api_github_import_dockerhub_register_post_volumes_type_0_item import (
    BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostVolumesType0Item,
)
from .body_reset_forgot_password_api_auth_forgot_password_post import BodyResetForgotPasswordApiAuthForgotPasswordPost
from .body_reset_reset_password_api_auth_reset_password_post import BodyResetResetPasswordApiAuthResetPasswordPost
from .body_verify_request_token_api_auth_request_verify_token_post import (
    BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost,
)
from .body_verify_verify_api_auth_verify_post import BodyVerifyVerifyApiAuthVerifyPost
from .capability_requirement import CapabilityRequirement
from .certificate_status import CertificateStatus
from .chat_message import ChatMessage
from .chat_request import ChatRequest
from .chat_simple_api_chat_simple_post_response_chat_simple_api_chat_simple_post import (
    ChatSimpleApiChatSimplePostResponseChatSimpleApiChatSimplePost,
)
from .chat_status import ChatStatus
from .claim_node_api_unodes_claim_post_request import ClaimNodeApiUnodesClaimPostRequest
from .clear_tailscale_auth_api_tailscale_container_clear_auth_post_response_clear_tailscale_auth_api_tailscale_container_clear_auth_post import (
    ClearTailscaleAuthApiTailscaleContainerClearAuthPostResponseClearTailscaleAuthApiTailscaleContainerClearAuthPost,
)
from .complete_setup_api_tailscale_complete_post_response_complete_setup_api_tailscale_complete_post import (
    CompleteSetupApiTailscaleCompletePostResponseCompleteSetupApiTailscaleCompletePost,
)
from .compose_env_var_info import ComposeEnvVarInfo
from .compose_parse_response import ComposeParseResponse
from .compose_service_info import ComposeServiceInfo
from .compose_service_info_healthcheck_type_0 import ComposeServiceInfoHealthcheckType0
from .compose_service_info_ports_item import ComposeServiceInfoPortsItem
from .configure_tailscale_serve_api_tailscale_configure_serve_post_response_configure_tailscale_serve_api_tailscale_configure_serve_post import (
    ConfigureTailscaleServeApiTailscaleConfigureServePostResponseConfigureTailscaleServeApiTailscaleConfigureServePost,
)
from .container_status import ContainerStatus
from .debug_docker_ports_api_services_debug_docker_ports_get_response_debug_docker_ports_api_services_debug_docker_ports_get import (
    DebugDockerPortsApiServicesDebugDockerPortsGetResponseDebugDockerPortsApiServicesDebugDockerPortsGet,
)
from .delete_imported_service_api_github_import_imported_service_id_delete_response_delete_imported_service_api_github_import_imported_service_id_delete import (
    DeleteImportedServiceApiGithubImportImportedServiceIdDeleteResponseDeleteImportedServiceApiGithubImportImportedServiceIdDelete,
)
from .delete_instance_api_instances_instance_id_delete_response_delete_instance_api_instances_instance_id_delete import (
    DeleteInstanceApiInstancesInstanceIdDeleteResponseDeleteInstanceApiInstancesInstanceIdDelete,
)
from .delete_wiring_api_instances_wiring_wiring_id_delete_response_delete_wiring_api_instances_wiring_wiring_id_delete import (
    DeleteWiringApiInstancesWiringWiringIdDeleteResponseDeleteWiringApiInstancesWiringWiringIdDelete,
)
from .deploy_instance_api_instances_instance_id_deploy_post_response_deploy_instance_api_instances_instance_id_deploy_post import (
    DeployInstanceApiInstancesInstanceIdDeployPostResponseDeployInstanceApiInstancesInstanceIdDeployPost,
)
from .deploy_request import DeployRequest
from .deployment import Deployment
from .deployment_deployed_config_type_0 import DeploymentDeployedConfigType0
from .deployment_mode import DeploymentMode
from .deployment_mode_mode import DeploymentModeMode
from .deployment_status import DeploymentStatus
from .detected_compose_file import DetectedComposeFile
from .disable_integration_auto_sync_api_instances_instance_id_sync_disable_post_response_disable_integration_auto_sync_api_instances_instance_id_sync_disable_post import (
    DisableIntegrationAutoSyncApiInstancesInstanceIdSyncDisablePostResponseDisableIntegrationAutoSyncApiInstancesInstanceIdSyncDisablePost,
)
from .discover_peers_api_unodes_discover_peers_get_response_discover_peers_api_unodes_discover_peers_get import (
    DiscoverPeersApiUnodesDiscoverPeersGetResponseDiscoverPeersApiUnodesDiscoverPeersGet,
)
from .docker_hub_image_info import DockerHubImageInfo
from .docker_hub_import_request import DockerHubImportRequest
from .docker_hub_scan_response import DockerHubScanResponse
from .enable_https_provisioning_api_tailscale_container_enable_https_post_response_enable_https_provisioning_api_tailscale_container_enable_https_post import (
    EnableHttpsProvisioningApiTailscaleContainerEnableHttpsPostResponseEnableHttpsProvisioningApiTailscaleContainerEnableHttpsPost,
)
from .enable_integration_auto_sync_api_instances_instance_id_sync_enable_post_response_enable_integration_auto_sync_api_instances_instance_id_sync_enable_post import (
    EnableIntegrationAutoSyncApiInstancesInstanceIdSyncEnablePostResponseEnableIntegrationAutoSyncApiInstancesInstanceIdSyncEnablePost,
)
from .enabled_request import EnabledRequest
from .env_config_update_request import EnvConfigUpdateRequest
from .env_var_config_item import EnvVarConfigItem
from .env_var_config_request import EnvVarConfigRequest
from .environment_info import EnvironmentInfo
from .error_model import ErrorModel
from .error_model_detail_type_1 import ErrorModelDetailType1
from .export_env_vars_api_services_name_env_export_get_response_export_env_vars_api_services_name_env_export_get import (
    ExportEnvVarsApiServicesNameEnvExportGetResponseExportEnvVarsApiServicesNameEnvExportGet,
)
from .find_providers_api_providers_find_post_response_200_item import FindProvidersApiProvidersFindPostResponse200Item
from .generate_tailscale_config_api_tailscale_generate_config_post_response_generate_tailscale_config_api_tailscale_generate_config_post import (
    GenerateTailscaleConfigApiTailscaleGenerateConfigPostResponseGenerateTailscaleConfigApiTailscaleGenerateConfigPost,
)
from .get_all_statuses_api_services_status_get_response_get_all_statuses_api_services_status_get import (
    GetAllStatusesApiServicesStatusGetResponseGetAllStatusesApiServicesStatusGet,
)
from .get_all_statuses_api_services_status_get_response_get_all_statuses_api_services_status_get_additional_property import (
    GetAllStatusesApiServicesStatusGetResponseGetAllStatusesApiServicesStatusGetAdditionalProperty,
)
from .get_caddy_status_api_tailscale_caddy_status_get_response_get_caddy_status_api_tailscale_caddy_status_get import (
    GetCaddyStatusApiTailscaleCaddyStatusGetResponseGetCaddyStatusApiTailscaleCaddyStatusGet,
)
from .get_defaults_api_instances_wiring_defaults_get_response_get_defaults_api_instances_wiring_defaults_get import (
    GetDefaultsApiInstancesWiringDefaultsGetResponseGetDefaultsApiInstancesWiringDefaultsGet,
)
from .get_docker_details_api_services_name_docker_get_response_get_docker_details_api_services_name_docker_get import (
    GetDockerDetailsApiServicesNameDockerGetResponseGetDockerDetailsApiServicesNameDockerGet,
)
from .get_docker_status_api_services_docker_status_get_response_get_docker_status_api_services_docker_status_get import (
    GetDockerStatusApiServicesDockerStatusGetResponseGetDockerStatusApiServicesDockerStatusGet,
)
from .get_enabled_state_api_services_name_enabled_get_response_get_enabled_state_api_services_name_enabled_get import (
    GetEnabledStateApiServicesNameEnabledGetResponseGetEnabledStateApiServicesNameEnabledGet,
)
from .get_env_config_api_services_name_env_get_response_get_env_config_api_services_name_env_get import (
    GetEnvConfigApiServicesNameEnvGetResponseGetEnvConfigApiServicesNameEnvGet,
)
from .get_integration_sync_status_api_instances_instance_id_sync_status_get_response_get_integration_sync_status_api_instances_instance_id_sync_status_get import (
    GetIntegrationSyncStatusApiInstancesInstanceIdSyncStatusGetResponseGetIntegrationSyncStatusApiInstancesInstanceIdSyncStatusGet,
)
from .get_provider_api_providers_provider_id_get_response_get_provider_api_providers_provider_id_get import (
    GetProviderApiProvidersProviderIdGetResponseGetProviderApiProvidersProviderIdGet,
)
from .get_provider_missing_api_providers_provider_id_missing_get_response_get_provider_missing_api_providers_provider_id_missing_get import (
    GetProviderMissingApiProvidersProviderIdMissingGetResponseGetProviderMissingApiProvidersProviderIdMissingGet,
)
from .get_providers_by_capability_api_providers_capability_capability_get_response_200_item import (
    GetProvidersByCapabilityApiProvidersCapabilityCapabilityGetResponse200Item,
)
from .get_selected_api_providers_selected_get_response_get_selected_api_providers_selected_get import (
    GetSelectedApiProvidersSelectedGetResponseGetSelectedApiProvidersSelectedGet,
)
from .get_service_api_services_name_get_response_get_service_api_services_name_get import (
    GetServiceApiServicesNameGetResponseGetServiceApiServicesNameGet,
)
from .get_service_config_api_services_name_config_get_response_get_service_config_api_services_name_config_get import (
    GetServiceConfigApiServicesNameConfigGetResponseGetServiceConfigApiServicesNameConfigGet,
)
from .get_service_connection_info_api_services_name_connection_info_get_response_get_service_connection_info_api_services_name_connection_info_get import (
    GetServiceConnectionInfoApiServicesNameConnectionInfoGetResponseGetServiceConnectionInfoApiServicesNameConnectionInfoGet,
)
from .get_service_status_api_services_name_status_get_response_get_service_status_api_services_name_status_get import (
    GetServiceStatusApiServicesNameStatusGetResponseGetServiceStatusApiServicesNameStatusGet,
)
from .get_services_by_capability_api_services_by_capability_capability_get_response_200_item import (
    GetServicesByCapabilityApiServicesByCapabilityCapabilityGetResponse200Item,
)
from .get_setup_state_api_wizard_setup_state_get_response_get_setup_state_api_wizard_setup_state_get import (
    GetSetupStateApiWizardSetupStateGetResponseGetSetupStateApiWizardSetupStateGet,
)
from .get_tailnet_settings_api_tailscale_container_tailnet_settings_get_response_get_tailnet_settings_api_tailscale_container_tailnet_settings_get import (
    GetTailnetSettingsApiTailscaleContainerTailnetSettingsGetResponseGetTailnetSettingsApiTailscaleContainerTailnetSettingsGet,
)
from .git_hub_import_request import GitHubImportRequest
from .git_hub_scan_response import GitHubScanResponse
from .git_hub_url_info import GitHubUrlInfo
from .health_response import HealthResponse
from .http_validation_error import HTTPValidationError
from .hugging_face_models_response import HuggingFaceModelsResponse
from .hugging_face_status_response import HuggingFaceStatusResponse
from .import_service_request import ImportServiceRequest
from .import_service_response import ImportServiceResponse
from .imported_service_config import ImportedServiceConfig
from .imported_service_config_source_type import ImportedServiceConfigSourceType
from .install_service_api_services_name_install_post_response_install_service_api_services_name_install_post import (
    InstallServiceApiServicesNameInstallPostResponseInstallServiceApiServicesNameInstallPost,
)
from .installation_guide import InstallationGuide
from .instance import Instance
from .instance_config import InstanceConfig
from .instance_config_values import InstanceConfigValues
from .instance_create import InstanceCreate
from .instance_create_config import InstanceCreateConfig
from .instance_outputs import InstanceOutputs
from .instance_outputs_capability_values import InstanceOutputsCapabilityValues
from .instance_outputs_env_vars import InstanceOutputsEnvVars
from .instance_status import InstanceStatus
from .instance_summary import InstanceSummary
from .instance_update import InstanceUpdate
from .instance_update_config_type_0 import InstanceUpdateConfigType0
from .integration_type import IntegrationType
from .join_token_create import JoinTokenCreate
from .join_token_response import JoinTokenResponse
from .kubernetes_cluster import KubernetesCluster
from .kubernetes_cluster_create import KubernetesClusterCreate
from .kubernetes_cluster_create_labels import KubernetesClusterCreateLabels
from .kubernetes_cluster_labels import KubernetesClusterLabels
from .kubernetes_cluster_status import KubernetesClusterStatus
from .leader_info_response import LeaderInfoResponse
from .list_capabilities_api_providers_capabilities_get_response_200_item import (
    ListCapabilitiesApiProvidersCapabilitiesGetResponse200Item,
)
from .list_catalog_api_services_catalog_get_response_200_item import ListCatalogApiServicesCatalogGetResponse200Item
from .list_imported_services_api_github_import_imported_get_response_200_item import (
    ListImportedServicesApiGithubImportImportedGetResponse200Item,
)
from .list_providers_api_providers_get_response_200_item import ListProvidersApiProvidersGetResponse200Item
from .list_services_api_services_get_response_200_item import ListServicesApiServicesGetResponse200Item
from .login_response import LoginResponse
from .logs_response import LogsResponse
from .manager_versions_response import ManagerVersionsResponse
from .missing_key import MissingKey
from .mobile_connection_qr import MobileConnectionQR
from .mobile_connection_qr_connection_data import MobileConnectionQRConnectionData
from .model_access_status import ModelAccessStatus
from .platform_info import PlatformInfo
from .platform_info_os_type import PlatformInfoOsType
from .port_config import PortConfig
from .port_conflict_info import PortConflictInfo
from .port_override_request import PortOverrideRequest
from .preflight_check_response import PreflightCheckResponse
from .provider_query import ProviderQuery
from .quickstart_response import QuickstartResponse
from .refresh_config_api_settings_refresh_post_response_refresh_config_api_settings_refresh_post import (
    RefreshConfigApiSettingsRefreshPostResponseRefreshConfigApiSettingsRefreshPost,
)
from .register_service_request import RegisterServiceRequest
from .register_service_request_metadata_type_0 import RegisterServiceRequestMetadataType0
from .reset_tailscale_api_tailscale_container_reset_post_response_reset_tailscale_api_tailscale_container_reset_post import (
    ResetTailscaleApiTailscaleContainerResetPostResponseResetTailscaleApiTailscaleContainerResetPost,
)
from .resolve_env_vars_api_services_name_resolve_get_response_resolve_env_vars_api_services_name_resolve_get import (
    ResolveEnvVarsApiServicesNameResolveGetResponseResolveEnvVarsApiServicesNameResolveGet,
)
from .save_quickstart_config_api_wizard_quickstart_post_key_values import (
    SaveQuickstartConfigApiWizardQuickstartPostKeyValues,
)
from .save_quickstart_config_api_wizard_quickstart_post_response_save_quickstart_config_api_wizard_quickstart_post import (
    SaveQuickstartConfigApiWizardQuickstartPostResponseSaveQuickstartConfigApiWizardQuickstartPost,
)
from .save_setup_state_api_wizard_setup_state_put_response_save_setup_state_api_wizard_setup_state_put import (
    SaveSetupStateApiWizardSetupStatePutResponseSaveSetupStateApiWizardSetupStatePut,
)
from .save_setup_state_api_wizard_setup_state_put_state import SaveSetupStateApiWizardSetupStatePutState
from .selection_update import SelectionUpdate
from .selection_update_selected_providers_type_0 import SelectionUpdateSelectedProvidersType0
from .service_definition import ServiceDefinition
from .service_definition_create import ServiceDefinitionCreate
from .service_definition_create_environment import ServiceDefinitionCreateEnvironment
from .service_definition_create_metadata import ServiceDefinitionCreateMetadata
from .service_definition_create_ports import ServiceDefinitionCreatePorts
from .service_definition_environment import ServiceDefinitionEnvironment
from .service_definition_metadata import ServiceDefinitionMetadata
from .service_definition_ports import ServiceDefinitionPorts
from .service_definition_update import ServiceDefinitionUpdate
from .service_definition_update_environment_type_0 import ServiceDefinitionUpdateEnvironmentType0
from .service_definition_update_metadata_type_0 import ServiceDefinitionUpdateMetadataType0
from .service_definition_update_ports_type_0 import ServiceDefinitionUpdatePortsType0
from .service_deployment import ServiceDeployment
from .service_endpoint_request import ServiceEndpointRequest
from .service_info import ServiceInfo
from .service_token_request import ServiceTokenRequest
from .service_token_response import ServiceTokenResponse
from .set_default_api_instances_wiring_defaults_capability_put_response_set_default_api_instances_wiring_defaults_capability_put import (
    SetDefaultApiInstancesWiringDefaultsCapabilityPutResponseSetDefaultApiInstancesWiringDefaultsCapabilityPut,
)
from .set_enabled_state_api_services_name_enabled_put_response_set_enabled_state_api_services_name_enabled_put import (
    SetEnabledStateApiServicesNameEnabledPutResponseSetEnabledStateApiServicesNameEnabledPut,
)
from .settings_response import SettingsResponse
from .setup_request import SetupRequest
from .setup_status_response import SetupStatusResponse
from .shadow_header_config import ShadowHeaderConfig
from .start_caddy_container_api_tailscale_container_start_caddy_post_response_start_caddy_container_api_tailscale_container_start_caddy_post import (
    StartCaddyContainerApiTailscaleContainerStartCaddyPostResponseStartCaddyContainerApiTailscaleContainerStartCaddyPost,
)
from .start_tailscale_container_api_tailscale_container_start_post_response_start_tailscale_container_api_tailscale_container_start_post import (
    StartTailscaleContainerApiTailscaleContainerStartPostResponseStartTailscaleContainerApiTailscaleContainerStartPost,
)
from .start_tailscale_with_caddy_api_tailscale_container_start_with_caddy_post_response_start_tailscale_with_caddy_api_tailscale_container_start_with_caddy_post import (
    StartTailscaleWithCaddyApiTailscaleContainerStartWithCaddyPostResponseStartTailscaleWithCaddyApiTailscaleContainerStartWithCaddyPost,
)
from .tailscale_config import TailscaleConfig
from .template import Template
from .template_config_schema_item import TemplateConfigSchemaItem
from .template_source import TemplateSource
from .test_connection_api_tailscale_test_connection_post_response_test_connection_api_tailscale_test_connection_post import (
    TestConnectionApiTailscaleTestConnectionPostResponseTestConnectionApiTailscaleTestConnectionPost,
)
from .test_integration_connection_api_instances_instance_id_test_connection_post_response_test_integration_connection_api_instances_instance_id_test_connection_post import (
    TestIntegrationConnectionApiInstancesInstanceIdTestConnectionPostResponseTestIntegrationConnectionApiInstancesInstanceIdTestConnectionPost,
)
from .trigger_integration_sync_api_instances_instance_id_sync_post_response_trigger_integration_sync_api_instances_instance_id_sync_post import (
    TriggerIntegrationSyncApiInstancesInstanceIdSyncPostResponseTriggerIntegrationSyncApiInstancesInstanceIdSyncPost,
)
from .u_node import UNode
from .u_node_action_response import UNodeActionResponse
from .u_node_capabilities import UNodeCapabilities
from .u_node_heartbeat import UNodeHeartbeat
from .u_node_heartbeat_metrics import UNodeHeartbeatMetrics
from .u_node_labels import UNodeLabels
from .u_node_list_response import UNodeListResponse
from .u_node_metadata import UNodeMetadata
from .u_node_platform import UNodePlatform
from .u_node_registration_request import UNodeRegistrationRequest
from .u_node_registration_response import UNodeRegistrationResponse
from .u_node_role import UNodeRole
from .u_node_status import UNodeStatus
from .undeploy_instance_api_instances_instance_id_undeploy_post_response_undeploy_instance_api_instances_instance_id_undeploy_post import (
    UndeployInstanceApiInstancesInstanceIdUndeployPostResponseUndeployInstanceApiInstancesInstanceIdUndeployPost,
)
from .unified_import_request import UnifiedImportRequest
from .unified_scan_response import UnifiedScanResponse
from .unified_scan_response_source_type import UnifiedScanResponseSourceType
from .uninstall_service_api_services_name_uninstall_post_response_uninstall_service_api_services_name_uninstall_post import (
    UninstallServiceApiServicesNameUninstallPostResponseUninstallServiceApiServicesNameUninstallPost,
)
from .update_config_api_settings_config_put_updates import UpdateConfigApiSettingsConfigPutUpdates
from .update_cors_origins_api_tailscale_update_cors_post_response_update_cors_origins_api_tailscale_update_cors_post import (
    UpdateCorsOriginsApiTailscaleUpdateCorsPostResponseUpdateCorsOriginsApiTailscaleUpdateCorsPost,
)
from .update_cors_request import UpdateCorsRequest
from .update_env_config_api_services_name_env_put_response_update_env_config_api_services_name_env_put import (
    UpdateEnvConfigApiServicesNameEnvPutResponseUpdateEnvConfigApiServicesNameEnvPut,
)
from .update_imported_service_config_api_github_import_imported_service_id_config_put_response_update_imported_service_config_api_github_import_imported_service_id_config_put import (
    UpdateImportedServiceConfigApiGithubImportImportedServiceIdConfigPutResponseUpdateImportedServiceConfigApiGithubImportImportedServiceIdConfigPut,
)
from .update_selected_api_providers_selected_put_response_update_selected_api_providers_selected_put import (
    UpdateSelectedApiProvidersSelectedPutResponseUpdateSelectedApiProvidersSelectedPut,
)
from .update_service_config_api_settings_service_configs_service_id_put_updates import (
    UpdateServiceConfigApiSettingsServiceConfigsServiceIdPutUpdates,
)
from .upgrade_all_unodes_api_unodes_upgrade_all_post_response_upgrade_all_unodes_api_unodes_upgrade_all_post import (
    UpgradeAllUnodesApiUnodesUpgradeAllPostResponseUpgradeAllUnodesApiUnodesUpgradeAllPost,
)
from .upgrade_request import UpgradeRequest
from .upgrade_response import UpgradeResponse
from .user_create import UserCreate
from .user_read import UserRead
from .user_update import UserUpdate
from .validation_error import ValidationError
from .volume_config import VolumeConfig
from .wiring import Wiring
from .wiring_create import WiringCreate

__all__ = (
    "AccessUrls",
    "AccessUrlsEnvironments",
    "AccessUrlsEnvironmentsAdditionalProperty",
    "ActionResponse",
    "ApiKeysStep",
    "ApiKeysUpdateResponse",
    "ApplyDefaultsApiProvidersApplyDefaultsModePostResponseApplyDefaultsApiProvidersApplyDefaultsModePost",
    "AuthUrlResponse",
    "BearerResponse",
    "BodyAuthBearerLoginApiAuthJwtLoginPost",
    "BodyAuthCookieLoginApiAuthCookieLoginPost",
    "BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPost",
    "BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostEnvVarsType0Item",
    "BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostPortsType0Item",
    "BodyRegisterDockerhubServiceApiGithubImportDockerhubRegisterPostVolumesType0Item",
    "BodyResetForgotPasswordApiAuthForgotPasswordPost",
    "BodyResetResetPasswordApiAuthResetPasswordPost",
    "BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost",
    "BodyVerifyVerifyApiAuthVerifyPost",
    "CapabilityRequirement",
    "CertificateStatus",
    "ChatMessage",
    "ChatRequest",
    "ChatSimpleApiChatSimplePostResponseChatSimpleApiChatSimplePost",
    "ChatStatus",
    "ClaimNodeApiUnodesClaimPostRequest",
    "ClearTailscaleAuthApiTailscaleContainerClearAuthPostResponseClearTailscaleAuthApiTailscaleContainerClearAuthPost",
    "CompleteSetupApiTailscaleCompletePostResponseCompleteSetupApiTailscaleCompletePost",
    "ComposeEnvVarInfo",
    "ComposeParseResponse",
    "ComposeServiceInfo",
    "ComposeServiceInfoHealthcheckType0",
    "ComposeServiceInfoPortsItem",
    "ConfigureTailscaleServeApiTailscaleConfigureServePostResponseConfigureTailscaleServeApiTailscaleConfigureServePost",
    "ContainerStatus",
    "DebugDockerPortsApiServicesDebugDockerPortsGetResponseDebugDockerPortsApiServicesDebugDockerPortsGet",
    "DeleteImportedServiceApiGithubImportImportedServiceIdDeleteResponseDeleteImportedServiceApiGithubImportImportedServiceIdDelete",
    "DeleteInstanceApiInstancesInstanceIdDeleteResponseDeleteInstanceApiInstancesInstanceIdDelete",
    "DeleteWiringApiInstancesWiringWiringIdDeleteResponseDeleteWiringApiInstancesWiringWiringIdDelete",
    "DeployInstanceApiInstancesInstanceIdDeployPostResponseDeployInstanceApiInstancesInstanceIdDeployPost",
    "Deployment",
    "DeploymentDeployedConfigType0",
    "DeploymentMode",
    "DeploymentModeMode",
    "DeploymentStatus",
    "DeployRequest",
    "DetectedComposeFile",
    "DisableIntegrationAutoSyncApiInstancesInstanceIdSyncDisablePostResponseDisableIntegrationAutoSyncApiInstancesInstanceIdSyncDisablePost",
    "DiscoverPeersApiUnodesDiscoverPeersGetResponseDiscoverPeersApiUnodesDiscoverPeersGet",
    "DockerHubImageInfo",
    "DockerHubImportRequest",
    "DockerHubScanResponse",
    "EnabledRequest",
    "EnableHttpsProvisioningApiTailscaleContainerEnableHttpsPostResponseEnableHttpsProvisioningApiTailscaleContainerEnableHttpsPost",
    "EnableIntegrationAutoSyncApiInstancesInstanceIdSyncEnablePostResponseEnableIntegrationAutoSyncApiInstancesInstanceIdSyncEnablePost",
    "EnvConfigUpdateRequest",
    "EnvironmentInfo",
    "EnvVarConfigItem",
    "EnvVarConfigRequest",
    "ErrorModel",
    "ErrorModelDetailType1",
    "ExportEnvVarsApiServicesNameEnvExportGetResponseExportEnvVarsApiServicesNameEnvExportGet",
    "FindProvidersApiProvidersFindPostResponse200Item",
    "GenerateTailscaleConfigApiTailscaleGenerateConfigPostResponseGenerateTailscaleConfigApiTailscaleGenerateConfigPost",
    "GetAllStatusesApiServicesStatusGetResponseGetAllStatusesApiServicesStatusGet",
    "GetAllStatusesApiServicesStatusGetResponseGetAllStatusesApiServicesStatusGetAdditionalProperty",
    "GetCaddyStatusApiTailscaleCaddyStatusGetResponseGetCaddyStatusApiTailscaleCaddyStatusGet",
    "GetDefaultsApiInstancesWiringDefaultsGetResponseGetDefaultsApiInstancesWiringDefaultsGet",
    "GetDockerDetailsApiServicesNameDockerGetResponseGetDockerDetailsApiServicesNameDockerGet",
    "GetDockerStatusApiServicesDockerStatusGetResponseGetDockerStatusApiServicesDockerStatusGet",
    "GetEnabledStateApiServicesNameEnabledGetResponseGetEnabledStateApiServicesNameEnabledGet",
    "GetEnvConfigApiServicesNameEnvGetResponseGetEnvConfigApiServicesNameEnvGet",
    "GetIntegrationSyncStatusApiInstancesInstanceIdSyncStatusGetResponseGetIntegrationSyncStatusApiInstancesInstanceIdSyncStatusGet",
    "GetProviderApiProvidersProviderIdGetResponseGetProviderApiProvidersProviderIdGet",
    "GetProviderMissingApiProvidersProviderIdMissingGetResponseGetProviderMissingApiProvidersProviderIdMissingGet",
    "GetProvidersByCapabilityApiProvidersCapabilityCapabilityGetResponse200Item",
    "GetSelectedApiProvidersSelectedGetResponseGetSelectedApiProvidersSelectedGet",
    "GetServiceApiServicesNameGetResponseGetServiceApiServicesNameGet",
    "GetServiceConfigApiServicesNameConfigGetResponseGetServiceConfigApiServicesNameConfigGet",
    "GetServiceConnectionInfoApiServicesNameConnectionInfoGetResponseGetServiceConnectionInfoApiServicesNameConnectionInfoGet",
    "GetServicesByCapabilityApiServicesByCapabilityCapabilityGetResponse200Item",
    "GetServiceStatusApiServicesNameStatusGetResponseGetServiceStatusApiServicesNameStatusGet",
    "GetSetupStateApiWizardSetupStateGetResponseGetSetupStateApiWizardSetupStateGet",
    "GetTailnetSettingsApiTailscaleContainerTailnetSettingsGetResponseGetTailnetSettingsApiTailscaleContainerTailnetSettingsGet",
    "GitHubImportRequest",
    "GitHubScanResponse",
    "GitHubUrlInfo",
    "HealthResponse",
    "HTTPValidationError",
    "HuggingFaceModelsResponse",
    "HuggingFaceStatusResponse",
    "ImportedServiceConfig",
    "ImportedServiceConfigSourceType",
    "ImportServiceRequest",
    "ImportServiceResponse",
    "InstallationGuide",
    "InstallServiceApiServicesNameInstallPostResponseInstallServiceApiServicesNameInstallPost",
    "Instance",
    "InstanceConfig",
    "InstanceConfigValues",
    "InstanceCreate",
    "InstanceCreateConfig",
    "InstanceOutputs",
    "InstanceOutputsCapabilityValues",
    "InstanceOutputsEnvVars",
    "InstanceStatus",
    "InstanceSummary",
    "InstanceUpdate",
    "InstanceUpdateConfigType0",
    "IntegrationType",
    "JoinTokenCreate",
    "JoinTokenResponse",
    "KubernetesCluster",
    "KubernetesClusterCreate",
    "KubernetesClusterCreateLabels",
    "KubernetesClusterLabels",
    "KubernetesClusterStatus",
    "LeaderInfoResponse",
    "ListCapabilitiesApiProvidersCapabilitiesGetResponse200Item",
    "ListCatalogApiServicesCatalogGetResponse200Item",
    "ListImportedServicesApiGithubImportImportedGetResponse200Item",
    "ListProvidersApiProvidersGetResponse200Item",
    "ListServicesApiServicesGetResponse200Item",
    "LoginResponse",
    "LogsResponse",
    "ManagerVersionsResponse",
    "MissingKey",
    "MobileConnectionQR",
    "MobileConnectionQRConnectionData",
    "ModelAccessStatus",
    "PlatformInfo",
    "PlatformInfoOsType",
    "PortConfig",
    "PortConflictInfo",
    "PortOverrideRequest",
    "PreflightCheckResponse",
    "ProviderQuery",
    "QuickstartResponse",
    "RefreshConfigApiSettingsRefreshPostResponseRefreshConfigApiSettingsRefreshPost",
    "RegisterServiceRequest",
    "RegisterServiceRequestMetadataType0",
    "ResetTailscaleApiTailscaleContainerResetPostResponseResetTailscaleApiTailscaleContainerResetPost",
    "ResolveEnvVarsApiServicesNameResolveGetResponseResolveEnvVarsApiServicesNameResolveGet",
    "SaveQuickstartConfigApiWizardQuickstartPostKeyValues",
    "SaveQuickstartConfigApiWizardQuickstartPostResponseSaveQuickstartConfigApiWizardQuickstartPost",
    "SaveSetupStateApiWizardSetupStatePutResponseSaveSetupStateApiWizardSetupStatePut",
    "SaveSetupStateApiWizardSetupStatePutState",
    "SelectionUpdate",
    "SelectionUpdateSelectedProvidersType0",
    "ServiceDefinition",
    "ServiceDefinitionCreate",
    "ServiceDefinitionCreateEnvironment",
    "ServiceDefinitionCreateMetadata",
    "ServiceDefinitionCreatePorts",
    "ServiceDefinitionEnvironment",
    "ServiceDefinitionMetadata",
    "ServiceDefinitionPorts",
    "ServiceDefinitionUpdate",
    "ServiceDefinitionUpdateEnvironmentType0",
    "ServiceDefinitionUpdateMetadataType0",
    "ServiceDefinitionUpdatePortsType0",
    "ServiceDeployment",
    "ServiceEndpointRequest",
    "ServiceInfo",
    "ServiceTokenRequest",
    "ServiceTokenResponse",
    "SetDefaultApiInstancesWiringDefaultsCapabilityPutResponseSetDefaultApiInstancesWiringDefaultsCapabilityPut",
    "SetEnabledStateApiServicesNameEnabledPutResponseSetEnabledStateApiServicesNameEnabledPut",
    "SettingsResponse",
    "SetupRequest",
    "SetupStatusResponse",
    "ShadowHeaderConfig",
    "StartCaddyContainerApiTailscaleContainerStartCaddyPostResponseStartCaddyContainerApiTailscaleContainerStartCaddyPost",
    "StartTailscaleContainerApiTailscaleContainerStartPostResponseStartTailscaleContainerApiTailscaleContainerStartPost",
    "StartTailscaleWithCaddyApiTailscaleContainerStartWithCaddyPostResponseStartTailscaleWithCaddyApiTailscaleContainerStartWithCaddyPost",
    "TailscaleConfig",
    "Template",
    "TemplateConfigSchemaItem",
    "TemplateSource",
    "TestConnectionApiTailscaleTestConnectionPostResponseTestConnectionApiTailscaleTestConnectionPost",
    "TestIntegrationConnectionApiInstancesInstanceIdTestConnectionPostResponseTestIntegrationConnectionApiInstancesInstanceIdTestConnectionPost",
    "TriggerIntegrationSyncApiInstancesInstanceIdSyncPostResponseTriggerIntegrationSyncApiInstancesInstanceIdSyncPost",
    "UndeployInstanceApiInstancesInstanceIdUndeployPostResponseUndeployInstanceApiInstancesInstanceIdUndeployPost",
    "UnifiedImportRequest",
    "UnifiedScanResponse",
    "UnifiedScanResponseSourceType",
    "UninstallServiceApiServicesNameUninstallPostResponseUninstallServiceApiServicesNameUninstallPost",
    "UNode",
    "UNodeActionResponse",
    "UNodeCapabilities",
    "UNodeHeartbeat",
    "UNodeHeartbeatMetrics",
    "UNodeLabels",
    "UNodeListResponse",
    "UNodeMetadata",
    "UNodePlatform",
    "UNodeRegistrationRequest",
    "UNodeRegistrationResponse",
    "UNodeRole",
    "UNodeStatus",
    "UpdateConfigApiSettingsConfigPutUpdates",
    "UpdateCorsOriginsApiTailscaleUpdateCorsPostResponseUpdateCorsOriginsApiTailscaleUpdateCorsPost",
    "UpdateCorsRequest",
    "UpdateEnvConfigApiServicesNameEnvPutResponseUpdateEnvConfigApiServicesNameEnvPut",
    "UpdateImportedServiceConfigApiGithubImportImportedServiceIdConfigPutResponseUpdateImportedServiceConfigApiGithubImportImportedServiceIdConfigPut",
    "UpdateSelectedApiProvidersSelectedPutResponseUpdateSelectedApiProvidersSelectedPut",
    "UpdateServiceConfigApiSettingsServiceConfigsServiceIdPutUpdates",
    "UpgradeAllUnodesApiUnodesUpgradeAllPostResponseUpgradeAllUnodesApiUnodesUpgradeAllPost",
    "UpgradeRequest",
    "UpgradeResponse",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "ValidationError",
    "VolumeConfig",
    "Wiring",
    "WiringCreate",
)
