"""
Integration tests for memory server synchronization.

Generated by automation-agent from test cases in:
specs/features/memory-feedback.testcases.md

Test Cases Covered:
- TC-MF-009: Memory Server Sync Success (REQUIRES SECRETS)
- TC-MF-010: Memory Server Sync Failure with Retry (REQUIRES SECRETS)
- TC-MF-011: Sync Queue Persistence (REQUIRES SECRETS)
"""

import os
from unittest.mock import AsyncMock, patch

import pytest


# TC-MF-009: Memory Server Sync Success
@pytest.mark.integration
@pytest.mark.requires_secrets
async def test_memory_server_sync_success():
    """
    Test Case: TC-MF-009

    Steps:
    1. Submit feedback
    2. Background job processes sync queue
    3. Verify HTTP request sent to memory server
    4. Verify feedback document updated

    Expected:
    - HTTP POST sent to memory server
    - Response 200 OK
    - feedback.synced_to_server = true
    """
    from src.services.memory_feedback import MemoryFeedbackService
    from src.services.memory_server_sync import MemoryServerSyncService

    # Skip if no API key configured
    api_key = os.getenv("MEMORY_SERVER_API_KEY")
    if not api_key:
        pytest.skip("MEMORY_SERVER_API_KEY not configured")

    # Arrange
    feedback_service = MemoryFeedbackService()
    sync_service = MemoryServerSyncService()

    # Create test feedback
    feedback_id = await feedback_service.submit_feedback(
        memory_id="507f1f77bcf86cd799439011",
        user_id="507f1f77bcf86cd799439012",
        feedback_type="true",
    )

    # Act
    result = await sync_service.sync_feedback(feedback_id)

    # Assert
    assert result.success is True
    assert result.response_status == 200

    # Verify feedback updated
    feedback = await feedback_service.get_feedback(feedback_id)
    assert feedback.synced_to_server is True
    assert feedback.sync_attempts == 1
    assert feedback.last_sync_error is None


# TC-MF-010: Memory Server Sync Failure with Retry
@pytest.mark.integration
@pytest.mark.requires_secrets
async def test_memory_server_sync_retry_on_failure():
    """
    Test Case: TC-MF-010

    Steps:
    1. Submit feedback
    2. First sync attempt fails (503)
    3. Verify retry scheduled
    4. Second attempt succeeds

    Expected:
    - After failure: synced_to_server=false, sync_attempts=1, error logged
    - After success: synced_to_server=true, sync_attempts=2
    """
    from src.services.memory_feedback import MemoryFeedbackService
    from src.services.memory_server_sync import MemoryServerSyncService

    # Skip if no API key
    api_key = os.getenv("MEMORY_SERVER_API_KEY")
    if not api_key:
        pytest.skip("MEMORY_SERVER_API_KEY not configured")

    # Arrange
    feedback_service = MemoryFeedbackService()
    sync_service = MemoryServerSyncService()

    feedback_id = await feedback_service.submit_feedback(
        memory_id="507f1f77bcf86cd799439011",
        user_id="507f1f77bcf86cd799439012",
        feedback_type="false",
    )

    # Act - First attempt (mock 503 error)
    with patch.object(sync_service, "_make_request") as mock_request:
        mock_request.return_value = AsyncMock(status_code=503)
        result_1 = await sync_service.sync_feedback(feedback_id)

    # Assert - After first failure
    assert result_1.success is False
    feedback = await feedback_service.get_feedback(feedback_id)
    assert feedback.synced_to_server is False
    assert feedback.sync_attempts == 1
    assert feedback.last_sync_error is not None

    # Act - Second attempt (succeeds)
    result_2 = await sync_service.sync_feedback(feedback_id)

    # Assert - After success
    assert result_2.success is True
    feedback = await feedback_service.get_feedback(feedback_id)
    assert feedback.synced_to_server is True
    assert feedback.sync_attempts == 2


# TC-MF-011: Sync Queue Persistence
@pytest.mark.integration
@pytest.mark.requires_secrets
@pytest.mark.slow  # This test involves service restart simulation
async def test_sync_queue_persistence_across_restart():
    """
    Test Case: TC-MF-011

    Steps:
    1. Submit 5 feedbacks
    2. Mock memory server as unavailable
    3. Verify 5 items in sync queue
    4. Simulate service restart
    5. Verify 5 items still in queue
    6. Bring server back online
    7. Verify all 5 synced

    Expected: Sync queue persists across restart
    """
    from src.services.memory_feedback import MemoryFeedbackService
    from src.services.memory_server_sync import MemoryServerSyncService

    # Skip if no API key
    api_key = os.getenv("MEMORY_SERVER_API_KEY")
    if not api_key:
        pytest.skip("MEMORY_SERVER_API_KEY not configured")

    # Arrange
    feedback_service = MemoryFeedbackService()
    sync_service = MemoryServerSyncService()

    # Submit 5 feedbacks
    feedback_ids = []
    for i in range(5):
        fid = await feedback_service.submit_feedback(
            memory_id="507f1f77bcf86cd799439011",
            user_id="507f1f77bcf86cd799439012",
            feedback_type="true",
        )
        feedback_ids.append(fid)

    # Mock server unavailable
    with patch.object(sync_service, "_make_request") as mock_request:
        mock_request.return_value = AsyncMock(status_code=503)
        for fid in feedback_ids:
            await sync_service.sync_feedback(fid)

    # Assert - 5 items in queue (not synced)
    queue_size = await sync_service.get_queue_size()
    assert queue_size == 5

    # Simulate service restart (close and reopen connection)
    await sync_service.close()
    sync_service = MemoryServerSyncService()  # Fresh instance

    # Assert - Queue still has 5 items
    queue_size = await sync_service.get_queue_size()
    assert queue_size == 5

    # Bring server back online (real requests now)
    for fid in feedback_ids:
        result = await sync_service.sync_feedback(fid)
        assert result.success is True

    # Assert - All synced
    queue_size = await sync_service.get_queue_size()
    assert queue_size == 0
