#!/usr/bin/env python3
"""
Cross-platform Ushadow startup script.

This is the main entry point that can be called from:
- Linux/macOS: python3 setup/run.py [--quick] [--prod] [--no-admin]
- Windows: python setup/run.py [--quick] [--prod] [--no-admin]

It replaces the bash-specific logic in start-dev.sh with cross-platform Python.
"""

import argparse
import os
import sys
import subprocess
import secrets
import time
import json
from pathlib import Path

# Add setup directory to path for imports
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from setup_utils import validate_ports, ensure_secrets_yaml, find_available_redis_db, set_redis_db_env_marker
from start_utils import ensure_networks, check_infrastructure_running, start_infrastructure, wait_for_backend_health

# Configuration
APP_NAME = "ushadow"
APP_DISPLAY_NAME = "Ushadow"
DEFAULT_BACKEND_PORT = 8000
DEFAULT_WEBUI_PORT = 3000
INFRA_COMPOSE_FILE = "compose/docker-compose.infra.yml"
INFRA_PROJECT_NAME = "infra"
APP_COMPOSE_FILE = "docker-compose.yml"

# Colors (ANSI escape codes, works on modern Windows too)
class Colors:
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    BOLD = '\033[1m'
    NC = '\033[0m'  # No Color

def print_color(color: str, message: str):
    """Print colored message."""
    print(f"{color}{message}{Colors.NC}")

def print_header():
    """Print startup header."""
    print()
    print_color(Colors.BOLD, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print_color(Colors.BOLD, f"🚀 {APP_DISPLAY_NAME} Quick Start")
    print_color(Colors.BOLD, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()

def check_docker():
    """Check if Docker is available."""
    try:
        result = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print_color(Colors.GREEN, f"✅ Docker found: {result.stdout.strip()}")
            return True
    except FileNotFoundError:
        pass

    print_color(Colors.RED, "❌ Docker not found. Please install Docker Desktop.")
    return False

def generate_env_file(env_name: str, port_offset: int, env_file: Path, secrets_file: Path):
    """Generate .env file with configuration."""
    backend_port = DEFAULT_BACKEND_PORT + port_offset
    webui_port = DEFAULT_WEBUI_PORT + port_offset

    # Validate ports
    all_available, conflicts = validate_ports([backend_port, webui_port])
    if conflicts:
        print_color(Colors.RED, f"❌ Port conflict: {conflicts}")
        return None

    # Find available Redis database
    preferred_redis_db = (port_offset // 10) % 16
    redis_db = find_available_redis_db(preferred_redis_db, env_name)
    set_redis_db_env_marker(redis_db, env_name)

    # Set database names
    if env_name == APP_NAME:
        mongodb_database = APP_NAME
        compose_project_name = APP_NAME
    else:
        mongodb_database = f"{APP_NAME}_{env_name}"
        compose_project_name = f"{APP_NAME}-{env_name}"

    # Generate .env content
    env_content = f"""# {APP_DISPLAY_NAME} Environment Configuration
# Generated by setup/run.py
# DO NOT COMMIT - Contains environment-specific configuration

# ==========================================
# ENVIRONMENT & PROJECT NAMING
# ==========================================
ENV_NAME={env_name}
COMPOSE_PROJECT_NAME={compose_project_name}

# ==========================================
# PORT CONFIGURATION
# ==========================================
PORT_OFFSET={port_offset}
BACKEND_PORT={backend_port}
WEBUI_PORT={webui_port}

# ==========================================
# DATABASE ISOLATION
# ==========================================
MONGODB_DATABASE={mongodb_database}
REDIS_DATABASE={redis_db}

# ==========================================
# CORS & FRONTEND CONFIGURATION
# ==========================================
CORS_ORIGINS=http://localhost:{webui_port},http://127.0.0.1:{webui_port},http://localhost:{backend_port},http://127.0.0.1:{backend_port}
VITE_BACKEND_URL=http://localhost:{backend_port}
VITE_ENV_NAME={env_name}
HOST_IP=localhost

# Development mode
DEV_MODE=false
"""

    env_file.write_text(env_content)
    os.chmod(env_file, 0o600)

    print_color(Colors.GREEN, "✅ Environment configured")
    print(f"  Name:     {env_name}")
    print(f"  Project:  {compose_project_name}")
    print(f"  Backend:  {backend_port}")
    print(f"  WebUI:    {webui_port}")
    print(f"  Database: {mongodb_database}")
    print()

    # Ensure secrets.yaml exists
    created_new, _ = ensure_secrets_yaml(str(secrets_file))
    if created_new:
        print_color(Colors.GREEN, "✅ Generated security keys in secrets.yaml")
    else:
        print_color(Colors.GREEN, "✅ Security keys already configured")

    return {
        "backend_port": backend_port,
        "webui_port": webui_port,
    }

def start_services(dev_mode: bool):
    """Start infrastructure and application services."""
    # Ensure Docker networks
    print_color(Colors.BLUE, "🏗️  Starting infrastructure...")
    ensure_networks()

    # Check if infrastructure is running
    infra_running = check_infrastructure_running()
    if infra_running:
        print_color(Colors.GREEN, "   ✅ Infrastructure already running")
    else:
        print_color(Colors.YELLOW, "   Starting infrastructure...")
        success, message = start_infrastructure(INFRA_COMPOSE_FILE, INFRA_PROJECT_NAME)
        if success:
            print_color(Colors.GREEN, f"   ✅ {message}")
        else:
            print_color(Colors.RED, f"   ❌ {message}")
            return False

    print()

    # Start application
    print_color(Colors.BLUE, f"🚀 Starting {APP_DISPLAY_NAME} application...")
    print()

    override_file = "compose/overrides/dev-webui.yml" if dev_mode else "compose/overrides/prod-webui.yml"

    cmd = [
        "docker", "compose",
        "-f", APP_COMPOSE_FILE,
        "-f", override_file,
        "up", "-d", "--build"
    ]

    result = subprocess.run(cmd, cwd=str(PROJECT_ROOT))
    if result.returncode != 0:
        print_color(Colors.RED, "❌ Failed to start application")
        return False

    return True

def wait_and_open(backend_port: int, webui_port: int, open_browser: bool):
    """Wait for backend health and optionally open browser."""
    print()
    print("   Waiting for backend to be healthy...")
    time.sleep(3)

    healthy, elapsed = wait_for_backend_health(backend_port, timeout=60)

    print()
    if healthy:
        print_color(Colors.GREEN + Colors.BOLD, f"✅ {APP_DISPLAY_NAME} is ready!")
    else:
        print_color(Colors.YELLOW, "⚠️  Backend is starting... (may take a moment)")

    # Print success box
    print()
    print_color(Colors.BOLD, "╔════════════════════════════════════════════════════╗")
    print_color(Colors.BOLD, "║                                                    ║")
    print_color(Colors.BOLD, f"║  🚀 {APP_DISPLAY_NAME} is ready!                          ║")
    print_color(Colors.BOLD, "║                                                    ║")
    print_color(Colors.BOLD, f"║     http://localhost:{webui_port}                          ║")
    print_color(Colors.BOLD, "║                                                    ║")
    print_color(Colors.BOLD, "╚════════════════════════════════════════════════════╝")
    print()

    # First-time setup instructions
    print_color(Colors.BOLD, "📋 First-Time Setup:")
    print()
    print("  1. Open the web interface (link above)")
    print("  2. Complete the setup wizard:")
    print("     • Create admin account")
    print("     • Configure API keys (OpenAI, Deepgram, etc.)")
    print("     • Select LLM and memory providers")
    print()

    # Open browser if requested
    if open_browser:
        url = f"http://localhost:{webui_port}/register"
        print_color(Colors.BLUE, "🌐 Opening registration page...")

        import webbrowser
        webbrowser.open(url)

    # Helpful commands
    print_color(Colors.BOLD, "Helpful commands:")
    print("  Stop:    make down    (or: docker compose down)")
    print("  Restart: make restart")
    print("  Logs:    make logs    (or: docker compose logs -f)")
    print()

    print_color(Colors.GREEN + Colors.BOLD, "🎉 Setup complete!")
    print()

def main():
    parser = argparse.ArgumentParser(description=f"{APP_DISPLAY_NAME} Quick Start")
    parser.add_argument("--quick", action="store_true", help="Use defaults without prompts")
    parser.add_argument("--dev", action="store_true", help="Development mode with hot-reload")
    parser.add_argument("--prod", action="store_true", help="Production mode")
    parser.add_argument("--no-admin", action="store_true", help="Skip admin creation (use web wizard)")
    parser.add_argument("--reset", action="store_true", help="Reset configuration")
    args = parser.parse_args()

    # Determine mode
    dev_mode = args.dev and not args.prod

    # Change to project root
    os.chdir(PROJECT_ROOT)

    # Print header
    print_header()

    # Check Docker
    if not check_docker():
        sys.exit(1)

    print()

    # Configuration paths
    env_file = PROJECT_ROOT / ".env"
    config_dir = PROJECT_ROOT / "config"
    secrets_file = config_dir / "secrets.yaml"

    # Ensure config directory exists
    config_dir.mkdir(exist_ok=True)

    # Generate or use existing config
    if env_file.exists() and not args.reset:
        print_color(Colors.GREEN, "✅ Using existing configuration")
        # Read ports from existing .env
        env_content = env_file.read_text()
        backend_port = DEFAULT_BACKEND_PORT
        webui_port = DEFAULT_WEBUI_PORT
        for line in env_content.splitlines():
            if line.startswith("BACKEND_PORT="):
                backend_port = int(line.split("=")[1])
            elif line.startswith("WEBUI_PORT="):
                webui_port = int(line.split("=")[1])
        config = {"backend_port": backend_port, "webui_port": webui_port}
    else:
        print_color(Colors.BLUE, "🔧 Generating configuration...")
        print()
        config = generate_env_file(
            env_name=APP_NAME,
            port_offset=0,
            env_file=env_file,
            secrets_file=secrets_file
        )
        if not config:
            sys.exit(1)

    print()

    # Start services
    if not start_services(dev_mode):
        sys.exit(1)

    # Wait and optionally open browser
    wait_and_open(
        config["backend_port"],
        config["webui_port"],
        open_browser=(args.quick and args.no_admin)
    )

if __name__ == "__main__":
    main()
