# Production override - nginx serving built static files
# Usage: docker compose -f docker-compose.yml -f compose/overrides/prod-webui.yml up

services:
  webui:
    build:
      context: ./ushadow/frontend
      dockerfile: Dockerfile
      args:
        # Vite env vars are baked in at build time - must pass as build args
        VITE_ENV_NAME: ${VITE_ENV_NAME:-}
        VITE_API_URL: ${VITE_API_URL:-}
        VITE_CHRONICLE_URL: ${VITE_CHRONICLE_URL:-}
    ports:
      - "${WEBUI_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
